### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Scrinn** [miltann/Echelon-2#15]
Everytime I try to access the site and finish it's setup it prompts to me download "download"

**Comment by miltann** [comment]
Can you attach screenshots? Maybe any error messages you can retrieve from the PHP logs?

**Comment by Scrinn** [comment]
I don't see any logs other than people accessing the main part of my site but I made a video of it happening and the file it downloads and put it in a .zip for you
[ahhhhh.zip](https://github.com/miltann/Echelon-2/files/4397855/ahhhhh.zip)

**Comment by miltann** [comment]
Any chance your Echelon installation is corrupted? I hope you understand that its hard to pinpoint the root cause for this just based on the information you've given me. 
I suggest you try to reinstall it. Keep in mind that older Echelon versions and its database are not compatible with this newer one.

**Comment by Scrinn** [comment]
I deleted the database and it's path in FTP and recreated the database using the echelon.sql file and re-uploaded the echelon directory. I still get the same result sadly. And I do understand

**Comment by miltann** [comment]
What about your PHP version?

**Comment by Scrinn** [comment]
I use php 7.2

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by miltann** [comment]
If you still have issues, check the latest repository for updates. If that doesn't work, try to use PHP 5
